default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blog_api_development
  username: "<%= ENV['BLOG_API_DB_USR'] %>"
  password: "<%= ENV['BLOG_API_DB_PWORD'] %>"

test:
  <<: *default
  database: blog_api_test
  username: "<%= ENV['BLOG_API_DB_USR'] %>"
  password: "<%= ENV['BLOG_API_DB_PWORD'] %>"

production:
  <<: *default
  database: blog_api_production
  username: "<%= ENV['BLOG_API_DB_USR'] %>"
  password: "<%= ENV['BLOG_API_DB_PWORD'] %>"
